# Generated by Django 2.0.5 on 2018-05-09 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIINFO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField()),
                ('api_key', models.CharField(default='l5x8ay13aegnq946', max_length=250)),
                ('api_token', models.CharField(max_length=250)),
                ('dattime', models.DateTimeField()),
                ('order_type', models.CharField(choices=[('SL', 'SL'), ('Limit', 'Limit')], default='SL', max_length=50)),
                ('script_exposure', models.IntegerField(default=1)),
                ('cushion_price', models.IntegerField(null=True)),
            ],
            options={
                'managed': True,
                'db_table': 'trade_apiinfo',
            },
        ),
        migrations.CreateModel(
            name='TradeMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(db_column='Date_time')),
                ('script', models.CharField(max_length=150)),
                ('close_price', models.FloatField()),
                ('trade_pos', models.CharField(max_length=50)),
                ('entry_price', models.FloatField()),
                ('sl', models.FloatField(db_column='SL')),
                ('i_target_price', models.FloatField(db_column='I_target_price')),
                ('i_target_exit', models.FloatField(db_column='I_target_exit')),
                ('i_target_pl', models.FloatField(db_column='I_target_PL')),
                ('ii_target_price', models.FloatField(db_column='II_target_price')),
                ('ii_target_exit', models.FloatField(db_column='II_target_exit')),
                ('ii_target_pl', models.FloatField(db_column='II_target_PL')),
                ('trailing_exit', models.FloatField()),
                ('trailing_float', models.FloatField()),
                ('share_float', models.FloatField()),
            ],
            options={
                'managed': True,
                'db_table': 'trade_message',
            },
        ),
    ]
