# Generated by Django 2.0.5 on 2018-05-09 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trademsg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeMessageHFloat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(db_column='Date_time')),
                ('script', models.CharField(max_length=150)),
                ('close_price', models.FloatField()),
                ('trade_pos', models.CharField(max_length=50)),
                ('entry_price', models.FloatField()),
                ('sl', models.FloatField(db_column='SL')),
                ('i_target_price', models.FloatField(db_column='I_target_price')),
                ('i_target_exit', models.FloatField(db_column='I_target_exit')),
                ('i_target_pl', models.FloatField(db_column='I_target_PL')),
                ('ii_target_price', models.FloatField(db_column='II_target_price')),
                ('ii_target_exit', models.FloatField(db_column='II_target_exit')),
                ('ii_target_pl', models.FloatField(db_column='II_target_PL')),
                ('trailing_exit', models.FloatField()),
                ('trailing_float', models.FloatField()),
                ('share_float', models.FloatField()),
            ],
            options={
                'managed': True,
                'db_table': 'trade_messageHFloat',
            },
        ),
    ]
